import os

PATH_TO_OUT = os.path.join("..", "out")

DISPLAY_WIDTH = 900
DISPLAY_HEIGHT = DISPLAY_WIDTH
DISPLAY_DIMENSIONS = (DISPLAY_WIDTH, DISPLAY_HEIGHT)
ORIGIN = (DISPLAY_WIDTH / 2, DISPLAY_HEIGHT / 2)

CHRISTMAS_MODE = False
#  -> to try out: set to True

TAIL_LENGTH = 200 if not CHRISTMAS_MODE else 135

STEPS = 2000 if not CHRISTMAS_MODE else 1000

GRAVITATIONAL_ACCELERATION = 0.5
